---
# delete user

- name: Kill all process by user
  shell: pgrep -U {{ login_user }}|xargs kill -9
  ignore_errors: true
  

- name: delete users 
  user:
    name: '{{ login_user }}'
    state: absent
    remove: yes

- name: Delete group 
  group:
    name: '{{ login_user }}'
    state: absent

- name: Disable sudo user
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ login_user }}'
    line: ''
    validate: visudo -cf %s

- name: Del file sudoers.d
  file:
    dest: "/etc/sudoers.d/{{ login_user }}"
    state: absent
