---
- hosts: "{{ w_host | default('test') }}"
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
  - debug: var=ansible_all_ipv4_addresses
  - debug: var=ansible_default_ipv4.address
  - debug: var=ansible_default_ipv4.macaddress
  - debug: var=ansible_default_ipv4.interface

