---

- name: Install Apache Web server test
  hosts: "{{ w_host | default('test') }}"


  tasks:
  - name: Install Apache2
    yum: name=httpd state=latest

  - name: Autostart Apache
    service: name=httpd state=started enabled=yes
