---

- name: Install and configure NTP client
  hosts: "{{ w_host | default('test') }}"
  
  # sudo: yes

  vars:
    region: Europe
    city: Samara

  tasks:
    - name: Install ntp Centos
      yum: name=ntp state=present
      when: ansible_pkg_mgr == 'yum'
      
    - name: Install ntp Ubuntu
      apt: name=ntp state=present
      when: ansible_pkg_mgr == 'apt'
      
    - name: Remove localtime
      file:
        path: /etc/localtime
        state: absent

    - name: Create localtime
      file:
        src: "/usr/share/zoneinfo/{{ region }}/{{ city }}"
        path: /etc/localtime
        state: link

    - name: stat ntp.conf
      stat: path=/etc/ntp.conf
      register: ntp_stat
    
    - name: Move ntp.conf
      command: mv /etc/ntp.conf /etc/ntp.conf-bak
      when: ntp_stat.stat.exists

    - name: Copy config file
      copy: src=files/ntp.conf dest=/etc/ntp.conf mode=0644

    - name: Restart ntpd Ubuntu
      service: name=ntp state=restarted
      when: ansible_pkg_mgr == 'apt'

    - name: Ensure NTP is running Ubuntu
      service: name=ntp state=started enabled=yes
      when: ansible_pkg_mgr == 'apt'
    
    - name: Restart ntpd Centos
      service: name=ntpd state=restarted
      when: ansible_pkg_mgr == 'yum'

    - name: Ensure NTP is running Centos
      service: name=ntpd state=started enabled=yes
      when: ansible_pkg_mgr == 'yum'
    
