---

- name: Create new container proxmox
  hosts: "{{ w_host | default('test') }}"

  vars:
    vm_name:  dmaster1
    vm_ip: 192.168.1.129

    vmclone: 'storage-local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz'
    pmx_node: node-1
    pmx_storage: storage-local

    pmx_api_host: node-1
    pmx_api_user: root@pam
    pmx_api_passwd: PASSWORD1

    vm_ciuser: root
    vm_cipassword: "Passw0rd2"

    vm_ssh_port: 22
    vm_gw: "192.168.1.1"
    vm_dns: "8.8.8.8"
    vm_domain_search: "evolife.local"

    vm_pubkey: 'ssh-rsa XcH root@ansible'
    vm_cores: 4
    vm_memory: 2048
    vm_swap_size: 1024
    vm_hdd: 'storage-local:20'


  tasks:
  - name: install pip pip3
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: no
    vars:
      packages:
      #- python-pip
      - python3-pip 

  - name:  install proxmoxer pip
    pip:
      name: proxmoxer
      executable: pip

  - name:  install requests pip
    pip:
      name: requests
      executable: pip

  - name:  install proxmoxer pip3
    pip:
      name: proxmoxer
      executable: pip3

  - name:  install requests pip3
    pip:
      name: requests
      executable: pip3

  - name: get next id vm
    shell:
        vmid=$(pvesh get /cluster/nextid);
        echo $vmid
    register: idnewvm

  - name: Create new container
    community.general.proxmox:
      vmid: '{{ idnewvm.stdout }}'
      node: '{{ pmx_node }}'
      api_user: '{{ pmx_api_user }}'
      api_password: '{{ pmx_api_passwd }}'
      api_host: '{{ pmx_api_host }}'
      password: '{{ vm_cipassword }}'
      hostname: '{{ item.value1 }}'
      ostemplate: '{{ vmclone }}'
      netif: '{"net0":"name=eth0,gw={{ vm_gw }},ip={{ item.value2 }}/24,bridge=vmbr0"}'
      cores: '{{ vm_cores }}'
      memory: '{{ memory }}'
      disk: '{{ vm_hdd }}'
      swap: '{{ vm_swap_size }}'
      nameserver: '{{ vm_dns }}'
      searchdomain: '{{ vm_domain_search }}'
      onboot: yes
      pubkey: '{{ vm_pubkey }}'
      timeout: 300

  - name: Start container
    community.general.proxmox:
      vmid: '{{ idnewvm.stdout }}'
      api_user: '{{ pmx_api_user }}'
      api_password: '{{ pmx_api_passwd }}'
      api_host: '{{ pmx_api_host }}'
      state: started

  - name: Wait for start server
    wait_for:
      port: '{{ vm_ssh_port }}'
      host: '{{ item.value2 }}'
      delay: 10
      timeout: 120



