---

- name: Install and configure zabbix-client default
  hosts: "{{ w_host | default('test') }}"
  
  # become: true # если истина, то выполнятся все операции от имени root, вместо sudo

  vars:
    zabbix_agent: zabbix-agent
    zabbix_agent_service: zabbix-agent
    zabbix_agent_conf: /etc/zabbix/zabbix_agentd.conf
    zabbix_server: "192.168.1.78"

  tasks:
    - name: Creates directory etc for zabbix
      file:
        path: /etc/zabbix/zabbix_agent.conf.d
        state: directory
        owner: root
        group: root
        mode: 0644
        recurse: yes

    - name: Creates directory scripts for zabbix
      file:
        path: /etc/zabbix/scripts
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy config file
      copy: src=files/zabbix/zabbix_agent.conf.d/check_lftp_proceses.conf dest=/etc/zabbix/zabbix_agent.conf.d/check_lftp_proceses.conf mode=0644

    - name: Copy scripts file
      copy: src=files/zabbix/scripts/check_lftp.sh dest=/etc/zabbix/scripts/check_lftp.sh mode=0755

    - name: Starting the Zabbix Agent
      service: name='{{ zabbix_agent_service }}' state=restarted enabled=yes

