---
- name: Install ntp Ubuntu
  apt: 
    name: ntp 
    state: present
  block:
    - name: stat localtime
      stat: 
        path: "/usr/share/zoneinfo/{{ region }}/{{ city }}"
      register: localtime_stat  

    - name: Remove localtime
      file:
        path: /etc/localtime
        state: absent

    - name: Create localtime
      file:
        src: "/usr/share/zoneinfo/{{ region }}/{{ city }}"
        path: /etc/localtime
        state: link
  when: localtime_stat.stat.exists

- name: stat ntp.conf
  stat: 
    path: /etc/ntp.conf
  register: ntp_stat

- name: Move ntp.conf
  command: mv /etc/ntp.conf /etc/ntp.conf-bak
  when: ntp_stat.stat.exists

- name: Copy config file
  template: 
    src: ntp.conf 
    dest: /etc/ntp.conf 
    mode: 0644

- name: Restart ntpd Ubuntu
  service: 
    name: ntp 
    state: restarted

- name: Ensure NTP is running Ubuntu
  service: 
    name: ntp 
    state: started 
    enabled: yes



