---
- name: Check if Swarm has already been Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: Initialize Docker Swarm
  shell: >
        docker swarm init
        --advertise-addr={{ hostvars[item].ansible_ssh_host }}:2377
  when: swarm_status.rc != 0
  run_once: true
  tags: swarm

- name: Get the Manager join-token
  shell: docker swarm join-token --quiet manager
  register: manager_token
  tags: swarm

- name: Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token
  tags: swarm

- local_action: copy content="{{ manager_token.stdout }}" dest="/tmp/manager_token"
- local_action: copy content="{{ worker_token.stdout }}" dest="/tmp/worker_token"
- local_action: copy content="{{ hostvars[item].ansible_ssh_host }}" dest="/tmp/docker_swarm_man_ip"
