---
# ansible-playbook docker_swarm_proxmox_role.yml -e w_host=nd1
- name: create vm container
  hosts: nd1
  roles:
    - role: proxmox_vm_create_role

- name: install docker to vm
  hosts: docker-swarm
  roles:
    - role: docker_role

- name: init docker swarm
  hosts: docker-swarm
  roles:
    - role: docker_swarm_role




