---
- name: install nginx in cluster
  hosts: "{{ w_host | default('test') }}"

  vars:
    user_ct: testuser
    group_ct: testgroup
    working_dir: "/var/www/html"
 
  tasks:
    - name: Remove image
      docker_image:
        state: absent
        name: "nginx"

    - name: pull.
      docker_image:
        name: "nginx"
        source: pull
        timeout: 300

    - name: service create
      docker_swarm_service:
        name: 'nginx'
        image: 'nginx'
        mode: replicated
        replicas: 5
        user: '{{ user_ct }}'
        groups:
          - '{{ group_ct }}'
        restart_config:
          condition: 'on-failure'
          delay: 5s
          max_attempts: 3
          window: 120s
        constraints:
          - node.role == worker
        publish:
          - mode: host
            published_port: '8080'
            target_port: '80'
        # healthcheck:
        #   test: ["CMD", "curl", "--fail", "http://nginx.host.com"]
        #   interval: 1m30s
        #   timeout: 10s
        #   retries: 3
        #   start_period: 30s


