---
- name: Repo zabbix for Centos 7
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    state: present
    validate_certs: no
  # when: ansible_pkg_mgr == 'yum'
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"

- name: Repo zabbix for Centos 8
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm
    #name: https://repo.zabbix.com/zabbix/4.5/rhel/8/x86_64/zabbix-release-4.5-2.el8.noarch.rpm
    state: present
    validate_certs: no
    disable_gpg_check: yes
  # when: ansible_pkg_mgr == 'yum'
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "8"

- name: Repo zabbix for Centos 6
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"

- name: Install zabbix-agent Centos
  yum: 
    name: zabbix-agent 
    # state=latest











