---
# handlers file for docker_role



# Pull image specified by variable default_image from the Docker Hub
- name: Pull default Docker image
  docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Docker image ls
  shell: docker image ls
  register: dockerls

- debug:
    msg: "{{ dockerls }}"
