---
# tasks file for docker_swarm_role

- include: docker_swarm_init.yml
  when: item.key == '{{ ds_master }}'
  with_dict: '{{ vm_names }}'

- include: docker_swarm_add_manager.yml
  when: item.key == '{{ ds_master2 }}'
  with_dict: '{{ vm_names }}'

- set_fact: result1="{{ result1 }} + [ '{{ item.key | regex_search('.*work.*', multiline=True, ignorecase=True) }}' ]"
  with_dict: '{{ vm_names }}'

- include: docker_swarm_add_worker.yml
  when: item.key in result1
  with_dict: '{{ vm_names }}'



